### GENERAL SETTINGS ###

# Site settings
title: Datos Abiertos Bolivia
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://aru.org.bo/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#4e4e00" #"#F70031" 
  primary_rgb: "78,78,0" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#00004e" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/FundacionARU?fref=ts
  - title: twitter
    url: https://twitter.com/ARUFoundation
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 2588 Calle Pinilla (Esquina Avenida Arce)
    - Edificio Arcadia, Mezanine Oficina 111
    - San Jorge, La Paz - Bolivia.
email: achirino@aru.org.bo
tel: +591 2-2004492, +591 2-2004491 


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Werner Hernani
    position: Director Ejecutivo
    text: Es cofundador de la fundación e investigador lider de los grupos de Monitoreo y Evaluación y Economia Política. Trabajó en los Departamentos de Investigación del Banco Mundial y del Banco Inter-americano de Desarrollo en Washington, DC; el Instituto de Pesquiza Económica Aplicada en Río de Janeiro, Brasil y en la Unidad de Análisis de Política Económica y Social. También ha trabajado como consultor para diversas organizaciones internacionales y gobiernos de Latinoamérica, el Caribe, Asia Central y del Sur.
    img: werner.jpg
    social:
      - title: envelope #use for email address
        url: mailto:whl@aru.org.bo
      - title: facebook
        url: https://www.facebook.com/wernerhl?ref=ts&fref=ts
  - name: Alvaro Chirino
    position: Lider Unidad de Datos
    text: Alvaro, estadística en la Universidad Mayor de San Andrés. Tiene una especialidad en diseños de evaluación de las políticas públicas en la Universidad Católica de Bolivia, trabajó en el Instituto Nacional de Estadística en el departamento de calidad estadística,  en ARU es el Coordinador de la Unidad de Microdatos y la Encuesta.
    img: alvaro.jpg
    social:
      - title: envelope #use for email address
        url: mailto:achirino@aru.org.bo
      - title: twitter
        url: https://twitter.com/Estbolivia
  - name: Sherli Mamani
    position: Responsable de Procesamiento
    text: Dentro de la Fundación ARU, es la responsable de sistemas. Es graduada de la carrera de estadística de la Universidad Mayor de San Andrés y tiene un diplomado en Evaluación de Impacto de la Universidad Católica Boliviana.
    img: sherli.jpg
    social:
      - title: envelope #use for email address
        url: mailto:smamani@aru.org.bo
      - title: facebook
        url: https://www.facebook.com/sherli.mamanihuanca?fref=ts
  - name: Beatriz Mamani
    position: Responsable Recoleccion de Datos
    text: Dentro de Fundación ARU, es la responsable de los operativos de campo. Trabajó como asistente de investigación en el Instituto de Estadística Teórica y Aplicada de la Universidad Mayor de San Andrés, es graduada en Estadistica.
    img: beatriz.jpg
    social:
      - title: envelope #use for email address
        url: mailto:bmamani@aru.org.bo
      - title: facebook
        url: https://www.facebook.com/beatriz.mamani.106?fref=ts
    
# Clients information. Shown on Home and About pages.
clients:
  - name: IDRC
    img: client01.png
  - name: Think Tank
    img: client02.jpg
  - name: PEP-NET
    img: client03.png
  - name: CBMS
    img: client04.jpg
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "La Fundación ARU es una organización de investigación de políticas independiente y sin fines de lucro creada con el objetivo de promover investigación aplicada de alta calidad que informe e influencie el debate de políticas públicas en Bolivia."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Existe una desigualdad mundial que está obstaculizando el progreso hacia el perfeccionamiento. Por el momento, poco conocemos de las personas que tienen menos oportunidades, pero estas son las personas que más necesitan la atención del mundo. Convertir aspiraciones globales o nacionales para acabar con la pobreza, con cambios reales en la vida de las personas, implicará saber más acerca cómo viven las personas más pobres y cómo mejorar su capacidad de acceder y utilizar datos."
    author: Cartagena Data Festival 2015
    position: 